# Generated by Django 5.0.1 on 2024-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="video_url_source",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="url_source",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default="static/app/img/default_profile.jpg",
                upload_to="static/app/img/",
            ),
        ),
    ]
